services:
  - type: web
    name: task-manager-backend
    runtime: python
    rootDirectory: task_manager
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn task_manager.wsgi
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: your-database-url